import Navigation from "./navigation"
import Header from "./header"
import Head from 'next/head'
import React from "react"
import Footer from './footer/footer'
import HomeHeaderSection from "../pages/api/data/home/home-header-section"

const HomeLayout =({ preview, children })=>{

return (
<>

<section className="section">
    <div className="container">
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeaderSection />
<Navigation/>
<Header/>
</div>
</section>

<section className="section">
    <div className="container">
<main>{children}</main>
</div>
</section>
<Footer />


</>

)}

export default HomeLayout