import Navigation from "./navigation"
import Header from "./header"
import Head from 'next/head'
import React from "react"
import Footer from './footer/footer'
import { Grid } from "@material-ui/core"


const Layout =({ preview, children })=>{

return (
<>

<section className="section">
    <div className="container">
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Navigation/>
<Header/>
</div>
</section>

<section className="section">
    <div className="container">
<main>{children}</main>
</div>
</section>
<Footer className="mt-4r" />


</>

)}

export default Layout