---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: pages/api/data/home
  label: About Us
  create: documents
  match: about-us.json
- type: directory
  path: pages/api/data/home
  label: Test
  create: documents
  match: welcome-section.json
  templates:
  - test
- type: directory
  path: pages/api/data/home
  label: Test 2
  create: all
  match: welcome-section.json
- type: heading
  label: Content
upload_dir: src/images
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
